mobileu/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from . import views

admin.autodiscover()

urlpatterns = \
    patterns('',
             (r"^summernote/", include("django_summernote.urls")),
             (r'^grappelli/', include('grappelli.urls')),
             url(r'^admin/', include(admin.site.urls)),
             url(
                 r'^admin/communication/postcomment/publish/(?P<pk>\d+)$',
                 views.publish_postcomment,
                 name='pub.postcomment'
             ),
             url(
                 r'^admin/communication/postcomment/unpublish/(?P<pk>\d+)$',
                 views.unpublish_postcomment,
                 name='unpub.postcomment'
             ),
             url(
                 r'^admin/communication/chatmessage/publish/(?P<pk>\d+)$',
                 views.publish_chatmessage,
                 name='pub.chatmessage'
             ),
             url(
                 r'^admin/communication/chatmessage/unpublish/(?P<pk>\d+)$',
                 views.unpublish_chatmessage,
                 name='unpub.chatmessage'
             ),
             url(
                 r'^admin/communication/discussion/publish/(?P<pk>\d+)$',
                 views.publish_discussion,
                 name='pub.discussion'
             ),
             url(
                 r'^admin/communication/discussion/unpublish/(?P<pk>\d+)$',
                 views.unpublish_discussion,
                 name='unpub.discussion'
             ),
             ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

oneplus/urls.py
from django.conf.urls import url, include
from oneplus import result_views
from oneplus import views
import oneplus.auth_views
import oneplus.com_views
import oneplus.core_views
import oneplus.learn_views
import oneplus.misc_views
import oneplus.prog_views
import oneplus.public_views
import oneplus.sharing_views


public_patterns = [
    url(r"^badges/?$", oneplus.public_views.badges, name="badges"),
    url(r"^level/?$", oneplus.public_views.level, name="level"),
    url(r"^leaderboard/(?P<board_type>[a-zA-Z_]*)/?", oneplus.public_views.leaderboard, name="leaderboard"),
]

sharing_patterns = [
    url(r"^level/?$", oneplus.sharing_views.level, name="level"),
    url(r"^leaderboard/(?P<board_type>[a-zA-Z_]*)/?", oneplus.sharing_views.leaderboard, name="leaderboard"),
]

urlpatterns = [
    # Misc
    url(r"^$", oneplus.misc_views.arrive, name="arrive"),
    url(r"^about$", oneplus.misc_views.about, name="misc.about"),
    url(r"^contact$", oneplus.misc_views.contact, name="misc.contact"),
    url(r"^faq$", oneplus.misc_views.faq, name="misc.faq"),
    url(r"^landing$", oneplus.misc_views.welcome, name="misc.welcome"),
    url(r"^menu$", oneplus.core_views.menu, name="core.menu"),
    url(r"^onboarding$", oneplus.misc_views.onboarding, name="misc.onboarding"),
    url(r'^terms$', oneplus.misc_views.terms, name="misc.terms"),

    # Auth
    url(r"^login/?$", oneplus.auth_views.login, name="auth.login"),
    url(r"^signout$", oneplus.auth_views.signout, name="auth.signout"),
    url(r"^getconnected$", oneplus.auth_views.getconnected, name="auth.getconnected"),
    url(r"^a/(?P<token>\S+)$", oneplus.auth_views.autologin, name="auth.autologin"),
    url(r"^profile$", oneplus.auth_views.profile, name="auth.profile"),
    url(r"^edit_profile$", oneplus.auth_views.edit_profile, name="auth.edit_profile"),
    url(r'^signup$', oneplus.auth_views.signup, name="auth.signup"),
    url(r'^signup_form$', oneplus.auth_views.signup_form, name="auth.signup_form"),
    url(r'^signup_school_confirm$', oneplus.auth_views.signup_school_confirm,
        name="auth.signup_school_confirm"),
    url(r'^signup_form_normal$', oneplus.auth_views.signup_form_normal, name="auth.signup_form_normal"),
    url(r'^return_signup$', oneplus.auth_views.return_signup, name="auth.return_signup"),
    url(r'^return_signup_school_confirm$', oneplus.auth_views.return_signup_school_confirm,
        name="auth.return_signup_school_confirm"),
    url(r'^no_sms$', oneplus.auth_views.no_sms, name="auth.no_sms"),
    url(r'^changedetails$', oneplus.auth_views.change_details, name="auth.change_details"),
    url(r'^sms_reset$', oneplus.auth_views.sms_reset_password_link, name="auth.sms_reset_password"),
    url(r'^r/(?P<token>\S+)$', oneplus.auth_views.reset_password, name="auth.reset_password"),
    url(r'^accept_terms/?$', oneplus.auth_views.accept_terms, name="auth.accept_terms"),

    # Learn
    url(r"^home", oneplus.learn_views.home, name="learn.home"),
    url(r"^next$", oneplus.learn_views.nextchallenge, name="learn.next"),
    url(r"^right$", oneplus.learn_views.right, name="learn.right"),
    url(r"^wrong$", oneplus.learn_views.wrong, name="learn.wrong"),
    url(r"^golden_egg_splash", oneplus.learn_views.golden_egg_splash, name="learn.golden_egg_splash"),
    url(r"^event$", oneplus.learn_views.event, name="learn.event"),
    url(r"^event_right$", oneplus.learn_views.event_right, name="learn.event_right"),
    url(r"^event_wrong$", oneplus.learn_views.event_wrong, name="learn.event_wrong"),
    url(r"^redo$", oneplus.learn_views.redo, name="learn.redo"),
    url(r"^redo_right$", oneplus.learn_views.redo_right, name="learn.redo_right"),
    url(r"^redo_wrong$", oneplus.learn_views.redo_wrong, name="learn.redo_wrong"),
    url(r"^sumit$", oneplus.learn_views.sumit, name="learn.sumit"),
    url(r"^sumit_right$", oneplus.learn_views.sumit_right, name="learn.sumit_right"),
    url(r"^sumit_wrong$", oneplus.learn_views.sumit_wrong, name="learn.sumit_wrong"),
    url(r"^preview/(?P<questionid>\d+)$", oneplus.learn_views.adminpreview, name="learn.preview"),
    url(r"^sumit_level_up$", oneplus.learn_views.sumit_level_up, name="learn.sumit_level_up"),
    url(r"^preview/right/(?P<questionid>\d+)$",
        oneplus.learn_views.adminpreview_right,
        name="learn.preview.right"),
    url(r"^preview/wrong/(?P<questionid>\d+)$",
        oneplus.learn_views.adminpreview_wrong,
        name="learn.preview.wrong"),
    url(r"^welcome$", oneplus.misc_views.first_time, name="learn.first_time"),
    url(r"^report_question/(?P<questionid>\d+)/(?P<frm>\w{0,5})$", oneplus.learn_views.report_question,
        name="learn.report_question"),
    url(r"^event_splash_page", oneplus.learn_views.event_splash_page, name="learn.event_splash_page"),
    url(r"^event_start_page", oneplus.learn_views.event_start_page, name="learn.event_start_page"),
    url(r"^event_end_page", oneplus.learn_views.event_end_page, name="learn.event_end_page"),
    url(r"^sumit_end_page", oneplus.learn_views.sumit_end_page, name="learn.sumit_end_page"),

    # Communicate
    url(r"^inbox$", oneplus.com_views.inbox, name="com.inbox"),
    url(r"^inbox/(?P<messageid>\d+)$",
        oneplus.com_views.inbox_detail,
        name="com.inbox_detail"),
    url(r"^inbox_send", oneplus.com_views.inbox_send, name="com.inbox_send"),

    url(r"^chat$", oneplus.com_views.chatgroups, name="com.chatgroups"),
    url(r"^chat/(?P<chatid>\d+)$", oneplus.com_views.chat, name="com.chat"),

    url(r"^blog$", oneplus.com_views.blog_hero, name="com.bloghero"),
    url(r"^bloglist$", oneplus.com_views.blog_list, name="com.bloglist"),
    url(r"^blog/(?P<blogid>\d+)$", oneplus.com_views.blog, name="com.blog"),

    url(r"^report_response/(?P<report>\d+)$",
        oneplus.misc_views.report_response,
        name="com.represp"),
    url(r"^message_response/(?P<msg>\d+)$",
        oneplus.misc_views.message_response,
        name="com.msgresp"),
    url(r"^discussion_response/(?P<disc>\d+)$",
        oneplus.misc_views.discussion_response,
        name="com.discresp"),
    url(r"^sms_response/(?P<sms>\d+)$",
        oneplus.com_views.sms_response,
        name="com.smsresp"),
    url(r"^smsqueue/add/$", oneplus.com_views.add_sms, name="com.add_sms"),
    url(r"^smsqueue/(?P<sms>\d+)/$", oneplus.com_views.view_sms, name="com.view_sms"),
    url(r"^discussion_response_selected/(?P<disc>(\d+)(,\s*\d+)*)$",
        oneplus.misc_views.discussion_response_selected,
        name="com.discrespsel"),

    url(r"^blog_comment_response/(?P<pc>\d+)$",
        oneplus.misc_views.blog_comment_response,
        name="com.blogcomresp"),
    url(r"^blog_comment_response_selected/(?P<pc>(\d+)(,\s*\d+)*)$",
        oneplus.misc_views.blog_comment_response_selected,
        name="com.blogcomrespsel"),

    url(r"^chat_response/(?P<cm>\d+)$",
        oneplus.misc_views.chat_response,
        name="com.chatresp"),
    url(r"^chat_response_selected/(?P<cm>(\d+)(,\s*\d+)*)$",
        oneplus.misc_views.chat_response_selected,
        name="com.chatrespsel"),

    url(r"^message/add/$", oneplus.com_views.add_message, name="com.add_message"),
    url(r"^message/(?P<msg>\d+)/$", oneplus.com_views.view_message, name="com.view_message"),

    # Progress
    url(r"^ontrack$", oneplus.prog_views.ontrack, name="prog.ontrack"),
    url(r"^leader$", oneplus.prog_views.leader, name="prog.leader"),
    url(r"^points$", oneplus.prog_views.points, name="prog.points"),
    url(r"^leader/(?P<areaid>\d+)$",
        oneplus.prog_views.leader,
        name="prog.leader.id"),
    url(r"^badges/?$", oneplus.prog_views.badges, name="prog.badges"),
    url(r"^badges/(?P<badge_id>\d+)$", oneplus.prog_views.badges, name="prog.badges_single"),
    url(r'^djga/', include('google_analytics.urls')),

    # Public
    url(r"^public/", include(public_patterns, namespace="public")),

    # Sharing
    url(r"^share/", include(sharing_patterns, namespace="share")),

    # Dashboard
    url(r'^dashboard_data$', oneplus.misc_views.dashboard_data, name="dash.data"),
    url(r'^dashboard$', oneplus.misc_views.dashboard, name='dash.board'),

    # Reports
    url(r'^reports$', oneplus.misc_views.reports, name='reports.home'),
    url(r'^report_learner_report/(?P<mode>\d+)/(?P<region>\w*)$',
        oneplus.misc_views.report_learner,
        name="reports.learner"),
    url(r'^reports_learner_unique_regions$',
        oneplus.misc_views.reports_learner_unique_regions,
        name="reports.unique_regions"),
    url(r'^report_question_difficulty_report/(?P<mode>\d+)$',
        views.question_difficulty_report,
        name='reports.question_difficulty'),
    url(r'^report_sumit_list/$', oneplus.misc_views.report_sumit_list, name='report.sumit_list'),
    url(r'^report_sumit_report/(?P<mode>\d+)/(?P<sumit_id>\d+)', oneplus.misc_views.report_sumit,
        name='report.sumit'),

    #filtering for message admin
    url(r'^courses$', views.get_courses),
    url(r'^classes/(?P<course>\w+)$', views.get_classes),
    url(r'^users/$', views.get_users),
    url(r'^award_badge/(?P<learner_id>\d+)/(?P<scenario_id>\d+)$', oneplus.prog_views.award_badge, name="award.badge"),

    url(r"^admin/results/(?P<course>\d+)$",
        result_views.ResultsView.as_view(),
        name="results.home"),
]

oneplusmvp/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns(
    '',
    (r"^summernote/", include("django_summernote.urls")),
    url(r'^', include('oneplus.urls')),
    (r'^grappelli/', include('grappelli.urls')),
    url(r'^', include('mobileu.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('pwa.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

oneplus/forms.py
from django import forms
from django.core.validators import ValidationError
from validators import validate_mobile


def validate_username(username):
        if not validate_mobile(username):
            raise ValidationError('Please enter a valid cellphone number.')


class LoginForm(forms.Form):
    username = forms.CharField(label="Phone Number", validators=[validate_username])
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput
    )


class SmsPasswordForm(forms.Form):
    msisdn = forms.CharField(label="Phone Number")


class ResetPasswordForm(forms.Form):
    password = forms.CharField(
        label="New Password",
        widget=forms.PasswordInput
    )

    password_2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput
    )

oneplus/templates/prog/badges.html
{% extends "core/main.html" %}

{% block title %}Badges{% endblock %}
{% block page_descriptor_text %}Badges{% endblock %}

{% block content %}
    <article class="content squash-accent">
        <h1>All badges</h1>

        <div>
            {% for badge in badges %}

                <a href="{% url 'prog.badges_single' badge_id=badge.id %}" class="badgecontainer {% if not badge.achieved %}disabled-badge{% endif %}">
                    {% if badge.achieved %}
                        <div class="badge-counter background-color-accent">{{ badge.count }}</div>
                    {% endif %}
                    {% if badge.image %}
                        <img class="badge" src="{{ badge.image.url }}">
    {#                    <li class="badge" style="background-image: url('{{ badge.image.url }}')"></li>#}
                    {% else %}
                        <li class="badge" style="background-image: url('/static/img/icn_badges.png')"></li>
                    {% endif %}
                    <div class="text center-font badge-name"><p>{{ badge.name }}</p></div>
                </a>
            {% endfor %}
            <div class="clear"></div>
        </div>
    </article>

{% endblock %}

oneplus/templates/prog/golden_egg_splash.html
{% extends "core/main.html" %}

{% block title %}Golden Egg{% endblock %}

{% block page_descriptor_text %}Golden Egg{% endblock %}

{% block content %}
    <article class="content sunflower-yellow-accent">
        <h1 class="center-font color-accent">You've won a Golden Egg!</h1>

        <div class="img-container">
            <img class="limit-size" src="/media/img/splash/splash_golden_egg.png" width="100%" height="auto"/>
        </div>

        <h3>
            You've won this week's <span class="color-accent">Golden Egg</span>{% if golden_egg.points %} and
            {{ golden_egg.points }} points{% endif %}{% if golden_egg.airtime %} and R{{ golden_egg.airtime }}
            airtime{% endif %}{% if golden_egg.badge %} and a badge{% endif %}.
            {% if golden_egg.airtime %}You will be awarded your airtime next Monday.{% endif %}
        </h3>

        <a class="button" href="right">Continue</a>
    </article>
{% endblock content %}

oneplus/templates/prog/leader.html
{% extends "core/main.html" %}

{% block title %}Leaderboards{% endblock %}
{% block page_descriptor_text %}Leaderboards{% endblock %}

{% block content %}
    {% load humanize %}
    {% load oneplus_extras %}

    <article class="content squash-accent">
        {% if allow_sharing and SOCIAL_MEDIA_ACTIVE %}
            <article class="card border-color-accent" id="share-my">
                <div class="text heading" >
                    <h3 class="card-top-phrase share-heading">Share my...</h3>
                </div>
                <section class="top" >
                    <div class="center-font">
                        <ul class="link-bar">
                            <li><a class="inline" href="{% url 'share:leaderboard' board_type='class' %}">leaderboard position</a></li>
                            <li><a class="inline" href="{% url 'share:leaderboard' board_type='school' %}">school's leaderboard position</a></li>
                            <li><a class="inline" href="{% url 'share:leaderboard' board_type='national' %}">national position</a></li>
                        </ul>
                    </div>
                </section>
            </article>
        {% endif %}

        <div class="text heading">
            {% if position %}
                <p>{{ header_2 }} <span class="purple-front">{{ position|ordinal_extra:'sup' }} place</span></p>
            {% endif %}
        </div>

        {% if class_board %}
            <article class="card border-color-accent" id="class-leaderboard">
                <section class="top">
                    <div class="img-container">
                        <img class="limit-size" src="/media/img/leaderboard/leaderboard_class.png" width="100%" height="auto"/>
                    </div>
                    <h3 class="card-top-phrase">Grade Leaderboard</h3>
                </section>
                {% if class_board.position %}
                    <hr class="hr-accent" />
                    <section class="bottom">
                        <div class="center-font">{{ user.name }}, you're currently in</div>
                        <div class="center-font color-accent funky-number">{{ class_board.position|ordinal_extra:'sup' }} place</div>
                    </section>
                {% endif %}
                {% if class_board.active %}
                    <hr class="hr-accent" />
                    <section class="bottom">
                        <table class="card-table">
                            <tr><th style="width:25%"></th><th></th><th class="num superlightgrey-front" style="width:25%">Points</th></tr>
                            {% for pos in class_board.board %}
                                {% for participant in pos.members %}
                                    <tr>
                                        <td class="funky-number color-accent" style="width:25%">{% if participant.position %}{{ participant.position|stringformat:"d" }}{% endif %}</td>
                                        <td class="{% if participant.me %}color-accent {% endif %}overflow-auto-scroll">{{ participant.name }}</td>
                                        <td class="{% if participant.me %}color-accent {% endif %}num" style="width:25%">{{ pos.points }}</td>
                                    </tr>
                                {% endfor %}
                            {% endfor %}
                        </table>
                    </section>
                {% endif %}
                <hr class="hr-accent" />
                <section class="bottom">
                    <form action="#class-leaderboard" class="no-pad" method="post">{% csrf_token %}
                        {% if class_board.active %}
                            <input type="hidden" name="board.class.active" value="false" />
                            <div class="center-font"><input class="link card-link" type="submit" value="Show less"></div>
                        {% else %}
                            <input type="hidden" name="board.class.active" value="true" />
                            <div class="center-font"><input class="link card-link" type="submit" value="Show more"></div>
                        {% endif %}
                    </form>
                </section>
            </article>
        {% endif %}


        {% if school_board %}
            <article class="card border-color-accent" id="school-leaderboard">
                <section class="top">
                    <div class="img-container">
                        <img class="limit-size" src="/media/img/leaderboard/leaderboard_school.png" width="100%" height="auto"/>
                    </div>
                    <h3 class="card-top-phrase">School Leaderboard</h3>
                </section>
                {% if school_board.position %}
                    <hr class="hr-accent" />
                    <section class="bottom">
                        <div class="center-font">Your school is currently in</div>
                        <div class="center-font color-accent funky-number">{{ school_board.position|ordinal_extra:'sup' }} place</div>
                    </section>
                {% endif %}
                {% if school_board.active %}
                    <hr class="hr-accent" />
                    <section class="bottom">
                        <table class="card-table">
                            <tr><th style="width:25%"></th><th></th><th class="num superlightgrey-front" style="width:25%">Points</th></tr>
                            {% for pos in school_board.board %}
                                {% for participant in pos.members %}
                                    <tr>
                                        <td class="funky-number color-accent" style="width:25%">{{ participant.position|stringformat:"d" }}</td>
                                        <td class="{% if participant.me %}color-accent {% endif %}overflow-auto-scroll">{{ participant.name }}</td>
                                        <td class="{% if participant.me %}color-accent {% endif %}num" style="width:25%">{{ pos.points }}</td>
                                    </tr>
                                {% endfor %}
                            {% endfor %}
                        </table>
                    </section>
                {% endif %}
                <hr class="hr-accent" />
                <section class="bottom">
                    <form action="#school-leaderboard" class="no-pad" method="post">{% csrf_token %}
                        {% if school_board.active %}
                            <input type="hidden" name="board.school.active" value="false" />
                            <div class="center-font"><input class="link card-link" type="submit" value="Show less"></div>
                        {% else %}
                            <input type="hidden" name="board.school.active" value="true" />
                            <div class="center-font"><input class="link card-link" type="submit" value="Show more"></div>
                        {% endif %}
                    </form>
                </section>
            </article>
        {% endif %}


        {% if national_board %}
            <article class="card border-color-accent" id="national-leaderboard">
                <section class="top">
                    <div class="img-container">
                        <img class="limit-size" src="/media/img/leaderboard/leaderboard_national.png" width="100%" height="auto"/>
                    </div>
                    <h3 class="card-top-phrase">National Leaderboard</h3>
                </section>
                {% if national_board.position %}
                    <hr class="hr-accent" />
                    <section class="bottom">
                        <div class="center-font">{{ user.name }}, you're currently in</div>
                        <div class="center-font color-accent funky-number">{{ national_board.position|ordinal_extra:'sup' }} place</div>
                    </section>
                {% endif %}
                {% if national_board.active %}
                    <hr class="hr-accent" />
                    <section class="bottom">
                        <table class="card-table">
                            <tr><th style="width:25%"></th><th></th><th class="num superlightgrey-front" style="width:25%">Points</th></tr>
                            {% for pos in national_board.board %}
                                {% for participant in pos.members %}
                                    <tr>
                                        <td class="funky-number color-accent" style="width:25%">{{ participant.position|stringformat:"d" }}</td>
                                        <td class="{% if participant.me %}color-accent {% endif %}overflow-auto-scroll"><b>{{ participant.name }}</b><br />{{ participant.school }}</td>
                                        <td class="{% if participant.me %}color-accent {% endif %} num" style="width:25%">{{ pos.points }}</td>
                                    </tr>
                                {% endfor %}
                            {% endfor %}
                        </table>
                    </section>
                {% endif %}
                <hr class="hr-accent" />
                <section class="bottom">
                    <form action="#national-leaderboard" class="no-pad" method="post">{% csrf_token %}
                        {% if national_board.active %}
                            <input type="hidden" name="board.national.active" value="false" />
                            <div class="center-font"><input class="link card-link" type="submit" value="Show less"></div>
                        {% else %}
                            <input type="hidden" name="board.national.active" value="true" />
                            <div class="center-font"><input class="link card-link" type="submit" value="Show more"></div>
                        {% endif %}
                    </form>
                </section>
            </article>
        {% endif %}
    </article>

{% endblock %}

oneplus/templates/prog/ontrack.html
{% extends "core/main.html" %}

{% block title %}ON TRACK{% endblock %}

{% block content %}
<div class="menu">
    <a href="/menu"><div class="text heading green-back darkgrey-front"><li class="icon ontrack"></li><p>On Track</p></div></a>
</div>
    <div class="text heading darkgrey-back" style="padding-top: 15px ; padding-bottom: 5px"><p>OnTrack shows you how well
        you are doing for each section of the syllabus. You'll need to
        answer a few questions in each section before we're able to show
        you a score, until then it will appear empty</p></div>
    <div class="text heading darkgrey-back"><p>Your progress so far</p></div>

    <div class="menu">
        {% for mod in modules %}
            <div class="item text grey-back {% if mod.score > 80 %}green-front{% elif mod.score > 56 %}orange-front{% elif mod.score > -1 %}red-front{% else %}white-front{% endif %}">
                <p>{% if mod.module_link != None and mod.module_link != "" %}
                        <a href="//{{ mod.module_link }}" target="blank">{{ mod.name }}</a>
                    {% else %}
                        {{ mod.name }}
                    {% endif %}
                    <span class="right large-font">{% if mod.score > -1 %}{{ mod.score | floatformat:0 }}% {% else %}<li class="icon ontrack"></li>{% endif %}</span>
                </p>
            </div>
        {% endfor %}
    </div>

    <p class="darkgrey-back white-front center-font">Just remember: Your On Track score does not necessarily guarantee results in school.</p>

{% endblock %}

oneplus/templates/prog/points.html
{% extends "core/main.html" %}

{% block title %}POINTS{% endblock %}

{% block content %}
    <div class="menu">
    <a href="/menu"><div class="text heading purple-back darkgrey-front"><li class="icon points"></li><p>Points</p></div></a>
    </div>
    <div class="text heading darkgrey-back"><p>Your points earned<span class="purple-front large-font-normal pull-right">{{ state.points_points }}</span></p></div>
    <div class="content padded">
        <table class="borderless" width="100%">
            {% for mod in modules %}
                <tr class="item grey-back white-front">
                    <td class="body-copy vert-center wrap-words">{{ mod.name }}</td>
                    <td class="text-right body-copy vert-center slim-num-field">{{ mod.score }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}